# Apache Tomcat server port
server:
  port: 9090

# Configs for Hibernate and JDBC links
spring:
  security:
    user:
      name: elifcan
      password: 147852
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.111:5432/basiteticaret
    username: postgres
    password: BilgeHs2**
  jpa:
    hibernate:
      ddl-auto: update

logging:
  file:
    name: ecommerce.log
  logback:
    rollingpolicy:
      max-file-size: 2MB
  level:
    root: info

my-application:
  product-title: 'New Java HS2'
  default-price: 1000

my-jwt:
  secret-key: "lajljlkdjfkjalgjkfjglfkjalkfj"