# Apache Tomcat server port
server:
  port: 9090

# Configs for Hibernate and JDBC links
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecdb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
